define([], function() {
  return {
    "Ago": "Siden",
    "AllActions": "Alle handlinger",
    "AllItems": "Alle elementer",
    "AllLabel": "Alle",
    "ApplyStageFilter": "Filtrér på stadie",
    "April": "april",
    "AprilShort": "apr",
    "AreYouSureYouWantToDeleteThis": "Er du sikker på at du vil slette denne relation",
    "AreYouSureYouWantToDeleteThisItem": "Er du sikker på at du vil slette denne?",
    "AToZ": "A til Z",
    "Attachment": "Vedhæftning",
    "Attachments": "Vedhæftninger",
    "August": "august",
    "AugustShort": "aug",
    "Author": "Forfatter",
    "BasicGroupName": "Generelle indstillinger",
    "Call": "Ring til",
    "Cancel": "Annuler",
    "Category": "Kategori",
    "Cc": "Cc",
    "ChangeStage": "Skift stadie",
    "ChooseABusinessModuleToCreateWordTemplateFor": "Vælg et forretningsmodul at oprette en Word skabelon for",
    "Clear": "Ryd",
    "ClearWorkPointBrowserCache": "Ryd WorkPoint 365 browser cache",
    "Close": "Luk",
    "CloseThisDialog": "Luk denne dialog",
    "CollapseExpandEntityPanel": "Vis/Skjul entitets panelet",
    "Color": "Farve",
    "ColorGroupName": "Farver på diagonaler",
    "Completed": "Fuldført",
    "ConfigureWebPart": "Konfigurer Opgaveoversigt web part",
    "ConstraintsPassedWhenStarted": "Stadie begrænsninger håndteret ved start",
    "Content": "Indhold",
    "CurrentSite": "Dette site",
    "Dashboards": "Overblik",
    "Date": "Dato",
    "Day": "Dag",
    "Days": "Dage",
    "DeadlineExceeded": "Deadline er overskredet",
    "DeadlineIs": "Deadline er",
    "DeadlineSoon": "Deadline nærmer sig",
    "DeadlineWas": "Deadline var",
    "December": "december",
    "DecemberShort": "dec",
    "Deferred": "Udskudt",
    "Delete": "Slet",
    "DeleteConfirmation": "Bekræft sletning",
    "Description": "Beskrivelse",
    "Details": "Detaljer",
    "Direction": "Retning",
    "DisplayAs": "Vis som",
    "DisplayGroupName": "Visning",
    "Documents": "Dokumenter",
    "Download": "Hent",
    "DueDate": "Forfaldsdato",
    "Edit": "Rediger",
    "EditTemplate": "Rediger skabelon",
    "Emails": "E-mails",
    "EmailsEMM": "E-mails (EMM)",
    "EMMPropertyPaneDescription": "Indstillinger for Email Manager web part",
    "Enabled": "Slået til",
    "End": "Slut",
    "EndDate": "Slutdato",
    "EndTime": "Sluttid",
    "EntireWorkPointSolution": "Hele WorkPoint løsningen",
    "EntityFiltering": "Entitetsfiltrering",
    "EntitySite": "Entitets site",
    "Events": "Begivenheder",
    "ExternalUserLicenseDescription": "Ekstern bruger lisens",
    "February": "februar",
    "FebruaryShort": "feb",
    "Field": "Felt",
    "FileType": "Filtype",
    "FilterBy": "Filtrér på",
    "Filtering": "Filtrering",
    "Filters": "Filtre",
    "Friday": "fredag",
    "FridayShort": "f",
    "From": "Fra",
    "GeneralGroupName": "Generelle indstillinger",
    "GoTo": "Gå til",
    "GoToNextMonth": "Gå til næste måned",
    "GoToNextPage": "Gå til næste side",
    "GoToNextYear": "Gå til næste år",
    "GoToPreviousMonth": "Gå til sidste måned",
    "GoToPreviousPage": "Gå til forrige side",
    "GoToPreviousYear": "Gå til sidste år",
    "GoToTheSiteFor": "Gå til sitet for",
    "GoToToday": "Gå til idag",
    "GoUp": "Gå op",
    "GroupedListFieldLabel": "Vis relationer grupperet",
    "Home": "Hjem",
    "Hour": "Time",
    "Hours": "Timer",
    "IfYouRegretRecyclingEntityItCanBeRestored": "Hvis du fortryder kan den genskabes inde fra papirkurven",
    "Images": "Billeder",
    "Incoming": "Indgående",
    "InProgress": "I gang",
    "InSelectedList": "I den valgte liste",
    "IsEqualToEntityField": "Er ens med entitetsfelt",
    "ItemLimitFieldLabel": "Begræns hvor mange e-mails der vises pr side",
    "January": "januar",
    "JanuaryShort": "jan",
    "JobFailed": "Job fejlede",
    "JobSucceded": "Job gennemført",
    "Journal": "Journal",
    "JournalInfo": "Journal info",
    "JournalPropertyPaneDescription": "Indstillinger for Journal web part",
    "July": "juli",
    "JulyShort": "jul",
    "June": "juni",
    "JuneShort": "jun",
    "JustNow": "Lige nu",
    "LastModified": "Senest redigeret",
    "LicensedUserDescription": "Lisenseret bruger",
    "LimitedLicenseDescription": "Begrænset bruger lisens",
    "LinkToItem": "Link til denne",
    "List": "Liste",
    "ListViewPropertyPaneDescription": "Indstillinger for WorkPoint liste visnings web part",
    "Loading": "Henter",
    "LoadingRelations": "Henter relationer",
    "Location": "Lokation",
    "LookupField": "Opslags felt",
    "March": "marts",
    "MarchShort": "mar",
    "May": "maj",
    "MayShort": "maj",
    "Minute": "Minut",
    "Minutes": "Minutter",
    "Modified": "Redigerede",
    "Monday": "mandag",
    "MondayShort": "m",
    "Month": "Månede",
    "Months": "Måneder",
    "MoreActions": "Flere handlinger",
    "MoreUsers": "Flere brugere",
    "MyWorkPointSolution": "WorkPoint løsning",
    "NavigateToTheBusinessModuleWhereEntityWasRecycled": "Vil du gå til forretningsmodullisten hvor entiteten befandt sig?",
    "NeedHelp": "Brug for hjælp",
    "NewWordTemplate": "Ny Word skabelon",
    "No": "Nej",
    "NoActivity": "Ingen aktivitet for denne entitet",
    "NoEntityFiltering": "Ingen entitetsfiltrering",
    "NoItems": "Der er ingen relationer at vise her",
    "NoItemsToShowHere": "Ingen resultater at vise",
    "NoLicenseDescription": "Ingen lisens for denne bruger",
    "None": "Ingen",
    "NoSettings": "Indstillingerne for denne web part er ikke konfigureret",
    "NotStarted": "Ikke startet",
    "November": "november",
    "NovemberShort": "nov",
    "NumberOfItemsShown": "Antal resultater vist",
    "October": "oktober",
    "OctoberShort": "okt",
    "Ok": "Ok",
    "Open": "Åbn",
    "OpenANewMailComposerToTheAddress": "Åbn ny mail til adressen",
    "OpenLinkTo": "Åbn link til",
    "OpenStageLink": "Åbn stadie link",
    "OpenTemplate": "Åbn skabelon",
    "Outgoing": "Udgående",
    "ParentSite": "Forældre site",
    "PercentComplete": "% Færdig",
    "Preview": "Forhåndsvisning",
    "ProbabilityLabel": "Sandsynlighed",
    "ReallyDeleteThisSite": "Er du sikker på at du vil slette dette site",
    "ReallyRecycleThisEntity": "Vil du virkelig fjerne denne entitet?",
    "Relation": "Relation",
    "RelationPropertyPaneDescription": "Indstillinger for Relations web part",
    "Relations": "Relationer",
    "RelationTypeFieldLabel": "Relationstyper",
    "RemoveStageFilter": "Fjern stadie filtrering",
    "Responsible": "Ansvarlig",
    "RiskMatrixPropertyPaneDescription": "Indstillinger for Risk Matrix web part",
    "RootSite": "Rod site",
    "Saturday": "lørdag",
    "SaturdayShort": "l",
    "Scope": "Afgrænsning",
    "SelectA": "Vælg et",
    "SelectACustomDate": "Vælg en skræddersyet dato",
    "SelectEndDate": "Vælg slutdato",
    "SelectList": "Vælg liste",
    "SelectProbability": "Vælg et felt for sandsynlighed",
    "SelectSeverity": "Vælg et felt for alvorlighed",
    "SelectStartDate": "Vælg startdato",
    "SelectView": "Vælg en visning fra listen",
    "Sender": "Afsender",
    "Sent": "Sendte",
    "September": "september",
    "SeptemberShort": "sep",
    "SettingsError": "Relations web part er fejlkonfigureret. Gennemgå venligst dens indstillinger",
    "SeverityLabel": "Alvorlighed",
    "ShowAllRelatedEvents": "Vis alle relaterede begivenheder",
    "ShowCount": "Vis sammentælling",
    "ShowFolderFieldLabel": "Show folders",
    "ShowInactiveRelationFieldLabel": "Vis inaktive relationer",
    "ShowOnlyMyTasks": "Vis kun mine opgaver",
    "ShowPercentage": "Vis procent",
    "ShowSeverityVertical": "Vis alvorlighed lodret",
    "SiteCouldNotBeCreated": "Sitet kunne ikke oprettes",
    "SiteCreationIsUnderway": "Sitet er ved at blive oprettet",
    "SiteCreationStatusCouldNotBeCheckedDueToTheFollowingError": "Site oprettelses status kunne ikke tjekkes grundet følgende fejl",
    "Sorting": "Sortering",
    "Sources": "Kilder",
    "StageView": "Stadievisning",
    "Start": "Start",
    "StartDate": "Startdato",
    "StartedOn": "Dette stadie blev startet",
    "StartTime": "Starttid",
    "Status": "Status",
    "Subject": "Emne",
    "SuccessFullyLoaded": "Hentet korrekt",
    "Sunday": "søndag",
    "SundayShort": "s",
    "TabbedGrouping": "Gruppering",
    "TabbedView": "Fanebladsvisning",
    "TaskList": "Opgaveliste",
    "TaskOverdue": "Opgave er overskredet",
    "TaskOverviewPropertyPaneDescription": "Indstillinger for opgaveoversigt web part",
    "Tasks": "Opgaver",
    "TasksAreShown": "Opgaver er vist",
    "TaskShown": "Opgave er vist",
    "TasksOverdue": "Opgaver er overskredet",
    "TextColorInTiles": "Tekst farve i kvadrater",
    "TheEntityCouldNotBeRecycled": "Entiteten kunne ikke fjernes. Prøv igen og sikr dig at entiteten ikke ligger i papirkurven",
    "TheEntityHasBeenRecycled": "Entiteten er blevet fjernet",
    "Thursday": "torsdag",
    "ThursdayShort": "t",
    "Title": "Titel",
    "To": "Til",
    "Today": "I dag",
    "Tuesday": "tirsdag",
    "TuesdayShort": "t",
    "UseDateSlider": "Brug dato skyder",
    "Version": "Version",
    "Viewed": "Kiggede på",
    "Waiting": "Venter på en anden",
    "Wednesday": "onsdag",
    "WednesdayShort": "o",
    "Week": "Uge",
    "Weeks": "Uger",
    "WorkPoint365Administration": "WorkPoint 365 Administration",
    "WorkPointSupportCenter": "WorkPoint Support Center",
    "Year": "År",
    "Years": "År",
    "Yes": "Ja",
    "You": "Du",
    "YouCanAlsoCreateATemplateWithoutMailMerge": "Du kan også oprette en skabelon uden forretningsmodul brevfletningsfelter",
    "YouDoNotHavePermissionToPerformThisAction": "Du har ikke rettigheder til at udføre denne handling",
    "YouHaveNoWorkPoint365License": "Du har ingen WorkPoint 365 licens",
    "ZToA": "Z til A",
  }
});