define([], function () {
  return {
    "Ago": "Ago",
    "AllActions": "All actions",
    "AllItems": "All items",
    "AllLabel": "All",
    "ApplyStageFilter": "Apply stage filter",
    "April": "April",
    "AprilShort": "Apr",
    "AreYouSureYouWantToDeleteThis": "Are you sure you want to delete this relation",
    "AreYouSureYouWantToDeleteThisItem": "Are you sure you want to delete this item?",
    "AToZ": "A to Z",
    "Attachment": "Attachment",
    "Attachments": "Attachments",
    "August": "August",
    "AugustShort": "Aug",
    "Author": "Author",
    "BasicGroupName": "General settings",
    "Call": "Call",
    "Cancel": "Cancel",
    "Category": "Category",
    "Cc": "Cc",
    "ChangeStage": "Change stage",
    "ChooseABusinessModuleToCreateWordTemplateFor": "Choose a business module to create a Word template for",
    "Clear": "Clear",
    "ClearWorkPointBrowserCache": "Clear WorkPoint 365 browser cache",
    "Close": "Close",
    "CloseThisDialog": "Close this dialog",
    "CollapseExpandEntityPanel": "Expand/Collapse entity panel",
    "Color": "Color",
    "ColorGroupName": "Colors of diagonals",
    "Completed": "Completed",
    "ConfigureWebPart": "Configure task overview web part",
    "ConstraintsPassedWhenStarted": "Constraints passed when started",
    "Content": "Content",
    "CurrentSite": "Current site",
    "Dashboards": "Dashboards",
    "Date": "Date",
    "Day": "Day",
    "Days": "Days",
    "DeadlineExceeded": "Deadline has been exceeded",
    "DeadlineIs": "Deadline is",
    "DeadlineSoon": "Deadline is coming soon",
    "DeadlineWas": "Deadline was",
    "December": "December",
    "DecemberShort": "Dec",
    "Deferred": "Deferred",
    "Delete": "Delete",
    "DeleteConfirmation": "Delete confirmation",
    "Description": "Description",
    "Details": "Details",
    "Direction": "Direction",
    "DisplayAs": "Display as",
    "DisplayGroupName": "Display",
    "Documents": "Documents",
    "Download": "Download",
    "DueDate": "Due date",
    "Edit": "Edit",
    "EditTemplate": "Edit template",
    "Emails": "Emails",
    "EmailsEMM": "Emails (EMM)",
    "EMMPropertyPaneDescription": "Settings for the Email Manager web part",
    "Enabled": "Enabled",
    "End": "End",
    "EndDate": "End date",
    "EndTime": "End time",
    "EntireWorkPointSolution": "Entire WorkPoint solution",
    "EntityFiltering": "Entity filtering",
    "EntitySite": "Entity site",
    "Events": "Events",
    "ExternalUserLicenseDescription": "External user license",
    "February": "February",
    "FebruaryShort": "Feb",
    "Field": "Field",
    "FileType": "File type",
    "FilterBy": "Filter by",
    "Filtering": "Filtering",
    "Filters": "Filters",
    "Friday": "Friday",
    "FridayShort": "F",
    "From": "From",
    "GeneralGroupName": "General settings",
    "GoTo": "Go to",
    "GoToNextMonth": "Go to next month",
    "GoToNextPage": "Go to next page",
    "GoToNextYear": "Go to next year",
    "GoToPreviousMonth": "Go to previous month",
    "GoToPreviousPage": "Go to previous page",
    "GoToPreviousYear": "Go to previous year",
    "GoToTheSiteFor": "Go the site for",
    "GoToToday": "Go to today",
    "GoUp": "Go up",
    "GroupedListFieldLabel": "Show relations in grouped list",
    "Home": "Home",
    "Hour": "Hour",
    "Hours": "Hours",
    "IfYouRegretRecyclingEntityItCanBeRestored": "If you regret or change your mind, you can restore it from the recycle bin",
    "Images": "Images",
    "Incoming": "Incoming",
    "InProgress": "In Progress",
    "InSelectedList": "In selected list",
    "IsEqualToEntityField": "Is equal to entity field",
    "ItemLimitFieldLabel": "Limits how many emails are shown per page",
    "January": "January",
    "JanuaryShort": "Jan",
    "JobFailed": "The job failed",
    "JobSucceded": "The job succeded",
    "Journal": "Journal",
    "JournalInfo": "Journal info",
    "JournalPropertyPaneDescription": "Settings for the Journal web part.",
    "July": "July",
    "JulyShort": "Jul",
    "June": "June",
    "JuneShort": "Jun",
    "JustNow": "Just now",
    "LastModified": "Last modified",
    "LicensedUserDescription": "Licensed user",
    "LimitedLicenseDescription": "Limited user license",
    "LinkToItem": "Link to item",
    "List": "List",
    "ListViewPropertyPaneDescription": "Settings for the WorkPoint list view client side web part.",
    "Loading": "Loading",
    "LoadingRelations": "Loading relations",
    "Location": "Location",
    "LookupField": "Lookup field",
    "March": "March",
    "MarchShort": "Mar",
    "May": "May",
    "MayShort": "May",
    "Minute": "Minute",
    "Minutes": "Minutes",
    "Modified": "Modified",
    "Monday": "Monday",
    "MondayShort": "M",
    "Month": "Month",
    "Months": "Months",
    "MoreActions": "More actions",
    "MoreUsers": "More users",
    "MyWorkPointSolution": "My WorkPoint solution",
    "NavigateToTheBusinessModuleWhereEntityWasRecycled": "Navigate to the business module where the item resided?",
    "NeedHelp": "Need help",
    "NewWordTemplate": "New Word template",
    "No": "No",
    "NoActivity": "No activity for this entity",
    "NoEntityFiltering": "No entity filtering",
    "NoItems": "There are no items to show here.",
    "NoItemsToShowHere": "No items to show here",
    "NoLicenseDescription": "No license for this user",
    "None": "None",
    "NoSettings": "There are no settings for this web part.",
    "NotStarted": "Not Started",
    "November": "November",
    "NovemberShort": "Nov",
    "NumberOfItemsShown": "Number of items shown",
    "October": "October",
    "OctoberShort": "Oct",
    "Ok": "Ok",
    "Open": "Open",
    "OpenANewMailComposerToTheAddress": "Open a new mail composer to the address",
    "OpenLinkTo": "Open link to",
    "OpenStageLink": "Open stage link",
    "OpenTemplate": "Open template",
    "Outgoing": "Outgoing",
    "ParentSite": "Parent site",
    "PercentComplete": "% Complete",
    "Preview": "Preview",
    "ProbabilityLabel": "Probability",
    "ReallyDeleteThisSite": "Are you sure you wan't to delete this site",
    "ReallyRecycleThisEntity": "Really recycle this entity?",
    "Relation": "Relation",
    "RelationPropertyPaneDescription": "Settings for the WorkPoint 365 Relation client side web part.",
    "Relations": "Relations",
    "RelationTypeFieldLabel": "Relation types",
    "RemoveStageFilter": "Remove stage filter",
    "Responsible": "Responsible",
    "RiskMatrixPropertyPaneDescription": "Settings for the Risk Matrix client side web part.",
    "RootSite": "Root site",
    "Saturday": "Saturday",
    "SaturdayShort": "S",
    "Scope": "Scope",
    "SelectA": "Select a",
    "SelectACustomDate": "Select a custom date",
    "SelectEndDate": "Select end date",
    "SelectList": "Select list",
    "SelectProbability": "Select field for probability",
    "SelectSeverity": "Select field for severity",
    "SelectStartDate": "Select start date",
    "SelectView": "Select view in the list",
    "Sender": "Sender",
    "Sent": "Sent",
    "September": "September",
    "SeptemberShort": "Sep",
    "SettingsError": "Something went wrong with web properties.",
    "SeverityLabel": "Severity",
    "ShowAllRelatedEvents": "Show all related events",
    "ShowCount": "Show count",
    "ShowFolderFieldLabel": "Show folders",
    "ShowInactiveRelationFieldLabel": "Show inactive relations",
    "ShowOnlyMyTasks": "Show only my tasks",
    "ShowPercentage": "Show percentage",
    "ShowSeverityVertical": "Display the Severity vertically",
    "SiteCouldNotBeCreated": "Site could not be created",
    "SiteCreationIsUnderway": "Site creation is under way",
    "SiteCreationStatusCouldNotBeCheckedDueToTheFollowingError": "Site creation status could not be checked due to the following error",
    "Sorting": "Sorting",
    "Sources": "Sources",
    "StageView": "Stage view",
    "Start": "Start",
    "StartDate": "Start date",
    "StartedOn": "Started this stage on",
    "StartTime": "Start time",
    "Status": "Status",
    "Subject": "Subject",
    "SuccessFullyLoaded": "Successfully loaded",
    "Sunday": "Sunday",
    "SundayShort": "S",
    "TabbedGrouping": "Grouping",
    "TabbedView": "Tabbed view",
    "TaskList": "Task list",
    "TaskOverdue": "Task overdue",
    "TaskOverviewPropertyPaneDescription": "Settings for task overview web part",
    "Tasks": "Tasks",
    "TasksAreShown": "Tasks are shown",
    "TaskShown": "Task is shown",
    "TasksOverdue": "Tasks overdue",
    "TextColorInTiles": "Text color in tiles",
    "TheEntityCouldNotBeRecycled": "The entity could not be recycled, please try again or make sure that the item is not in the recycle bin",
    "TheEntityHasBeenRecycled": "The entity has been recycled",
    "Thursday": "Thursday",
    "ThursdayShort": "T",
    "Title": "Title",
    "To": "To",
    "Today": "Today",
    "Tuesday": "Tuesday",
    "TuesdayShort": "T",
    "UseDateSlider": "Use date slider",
    "Version": "Version",
    "Viewed": "Viewed",
    "Waiting": "Waiting on someone else",
    "Wednesday": "Wednesday",
    "WednesdayShort": "W",
    "Week": "Week",
    "Weeks": "Weeks",
    "WorkPoint365Administration": "WorkPoint 365 Administration",
    "WorkPointSupportCenter": "WorkPoint Support Center",
    "Year": "Year",
    "Years": "Years",
    "Yes": "Yes",
    "You": "You",
    "YouCanAlsoCreateATemplateWithoutMailMerge": "You can also create a template without business module mail merge fields",
    "YouDoNotHavePermissionToPerformThisAction": "You do not have permission to perform this action",
    "YouHaveNoWorkPoint365License": "You have no WorkPoint 365 license",
    "ZToA": "Z to A",
  }
});