define([], function () {
    return {
      "Ago": "Siden",
      "AllActions": "Alle handlinger",
      "AllItems": "Alle elementer",
      "AllLabel": "Alle",
      "ApplyStageFilter": "Filtrér på stadie",
      "April": "april",
      "AprilShort": "apr",
      "AreYouSureYouWantToDeleteThis": "Er du sikker på at du vil slette denne relasjonen",
      "AreYouSureYouWantToDeleteThisItem": "Er du sikker på at du vil slette denne?",
      "AToZ": "A til Z",
      "Attachment": "Vedlegg",
      "Attachments": "Vedlegg",
      "August": "august",
      "AugustShort": "aug",
      "Author": "Forfatter",
      "BasicGroupName": "Generelle innstillinger",
      "Call": "Ring til",
      "Cancel": "Avbryt",
      "Category": "Kategori",
      "Cc": "Cc",
      "ChangeStage": "Endre stadie",
      "ChooseABusinessModuleToCreateWordTemplateFor": "Velg en forretningsmodul å opprette en Word mal for",
      "Clear": "Tøm",
      "ClearWorkPointBrowserCache": "Tøm WorkPoint 365 netleser cache",
      "Close": "Lukk",
      "CloseThisDialog": "Lukk denne dialogen",
      "CollapseExpandEntityPanel": "Vis/Skjul entitets panelet",
      "Color": "Farge",
      "ColorGroupName": "Farger på diagonaler",
      "Completed": "Fullført",
      "ConfigureWebPart": "Konfigurer Oppgaveoversikt web part",
      "ConstraintsPassedWhenStarted": "Stadie begrensninger håndteret ved start",
      "Content": "Innhold",
      "CurrentSite": "Denne siten",
      "Dashboards": "Dashbord",
      "Date": "Dato",
      "Day": "Dag",
      "Days": "Dager",
      "DeadlineExceeded": "Deadline er overskredet",
      "DeadlineIs": "Deadline er",
      "DeadlineSoon": "Deadline nærmer sig",
      "DeadlineWas": "Deadline var",
      "December": "desember",
      "DecemberShort": "des",
      "Deferred": "Utsatt",
      "Delete": "Slett",
      "DeleteConfirmation": "Bekreft sletting",
      "Description": "Beskrivelse",
      "Details": "Detaljer",
      "Direction": "Rettning",
      "DisplayAs": "Vis som",
      "DisplayGroupName": "Visning",
      "Documents": "Dokumenter",
      "Download": "Hent",
      "DueDate": "Forfallsdato",
      "Edit": "Rediger",
      "EditTemplate": "Rediger mal",
      "Emails": "E-poster",
      "EmailsEMM": "E-poster (EMM)",
      "EMMPropertyPaneDescription": "Innstillinger for Email Manager web part",
      "Enabled": "Aktivert",
      "End": "Sluttid",
      "EndDate": "Sluttdato",
      "EndTime": "Sluttid",
      "EntireWorkPointSolution": "Hele WorkPoint løsningen",
      "EntityFiltering": "Entitetsfiltrering",
      "EntitySite": "Entitets site",
      "Events": "Hendelser",
      "ExternalUserLicenseDescription": "Ekstern brukerlisens",
      "February": "februar",
      "FebruaryShort": "feb",
      "Field": "Felt",
      "FileType": "Filtype",
      "FilterBy": "Filtrér på",
      "Filtering": "Filtrering",
      "Filters": "Filtre",
      "Friday": "fredag",
      "FridayShort": "f",
      "From": "Fra",
      "GeneralGroupName": "Generelle innstillinger",
      "GoTo": "Gå til",
      "GoToNextMonth": "Gå til neste måned",
      "GoToNextPage": "Gå til neste side",
      "GoToNextYear": "Gå til neste år",
      "GoToPreviousMonth": "Gå til forrige måned",
      "GoToPreviousPage": "Gå til forrige side",
      "GoToPreviousYear": "Gå til forrige år",
      "GoToTheSiteFor": "Gå til sitet for",
      "GoToToday": "Gå til idag",
      "GoUp": "Gå opp",
      "GroupedListFieldLabel": "Vis relationer gruppert",
      "Home": "Hjem",
      "Hour": "Time",
      "Hours": "Timer",
      "IfYouRegretRecyclingEntityItCanBeRestored": "Hvis du ombestemmer deg, kan du gjenopprette den fra papirkurven",
      "Images": "Bilder",
      "Incoming": "Inngående",
      "InProgress": "I gang",
      "InSelectedList": "I den valgte listen",
      "IsEqualToEntityField": "Er lik entitetsfeltet",
      "ItemLimitFieldLabel": "Begrens hvor mange e-poster som vises pr side",
      "January": "januar",
      "JanuaryShort": "jan",
      "JobFailed": "Jobben feilet",
      "JobSucceded": "Jobben er ferdig",
      "Journal": "Journal",
      "JournalInfo": "Journal info",
      "JournalPropertyPaneDescription": "Innstillinger for Journal web part",
      "July": "juli",
      "JulyShort": "jul",
      "June": "juni",
      "JuneShort": "jun",
      "JustNow": "Nå",
      "LastModified": "Sist endret",
      "LicensedUserDescription": "Lisensiert bruker",
      "LimitedLicenseDescription": "Begrenset brukerlisens",
      "LinkToItem": "Link til denne",
      "List": "Liste",
      "ListViewPropertyPaneDescription": "Innstillinger for WorkPoint listevisning web part",
      "Loading": "Henter",
      "LoadingRelations": "Henter relasjoner",
      "Location": "Lokasjon",
      "LookupField": "Oppslagsfelt",
      "March": "mars",
      "MarchShort": "mar",
      "May": "mai",
      "MayShort": "mai",
      "Minute": "Minutt",
      "Minutes": "Minutter",
      "Modified": "Endret",
      "Monday": "mandag",
      "MondayShort": "m",
      "Month": "Måned",
      "Months": "Måneder",
      "MoreActions": "Flere handlinger",
      "MoreUsers": "Flere brukere",
      "MyWorkPointSolution": "WorkPoint løsning",
      "NavigateToTheBusinessModuleWhereEntityWasRecycled": "Vil du gå til forretningsmodullisten hvor entiteten befant seg?",
      "NeedHelp": "Bruk for hjelp",
      "NewWordTemplate": "Ny Word mal",
      "No": "Nei",
      "NoActivity": "Ingen aktivitet for denne entitet",
      "NoEntityFiltering": "Ingen entitetsfiltrering",
      "NoItems": "Der er ingen relationer å vise her",
      "NoItemsToShowHere": "Ingen resultater å vise",
      "NoLicenseDescription": "Ingen lisens for denne brukeren",
      "None": "Ingen",
      "NoSettings": "Innstillingene for denne web part er ikke konfigurert",
      "NotStarted": "Ikke startet",
      "November": "november",
      "NovemberShort": "nov",
      "NumberOfItemsShown": "Antall resultater vist",
      "October": "oktober",
      "OctoberShort": "okt",
      "Ok": "Ok",
      "Open": "Åpne",
      "OpenANewMailComposerToTheAddress": "Åpne ny e-post til adressen",
      "OpenLinkTo": "Åpne link til",
      "OpenStageLink": "Åpne stadie link",
      "OpenTemplate": "Åpne mal",
      "Outgoing": "Utgående",
      "ParentSite": "Foreldre site",
      "PercentComplete": "% Ferdig",
      "Preview": "Forhåndsvisning",
      "ProbabilityLabel": "Sannsynlighet",
      "ReallyDeleteThisSite": "Er du sikker på at du vil slette denne siten",
      "ReallyRecycleThisEntity": "Vil du virkelig fjerne denne entiteten?",
      "Relation": "Relasjon",
      "RelationPropertyPaneDescription": "Innstillinger for Relasjon web part",
      "Relations": "Relasjoner",
      "RelationTypeFieldLabel": "Relasjonstyper",
      "RemoveStageFilter": "Fjern stadie filtrering",
      "Responsible": "Ansvarlig",
      "RiskMatrixPropertyPaneDescription": "Innstillinger for Risk Matrix web part",
      "RootSite": "Rot site",
      "Saturday": "lørdag",
      "SaturdayShort": "l",
      "Scope": "Avgrensning",
      "SelectA": "Velg et",
      "SelectACustomDate": "Velg en skreddersydd dato",
      "SelectEndDate": "Velg sluttdato",
      "SelectList": "Velg liste",
      "SelectProbability": "Velg et felt for sannsynlighet",
      "SelectSeverity": "Velg et felt for alvorlighet",
      "SelectStartDate": "Velg startdato",
      "SelectView": "Velg en visning fra listen",
      "Sender": "Avsender",
      "Sent": "Sendt",
      "September": "september",
      "SeptemberShort": "sep",
      "SettingsError": "Relations web part er feilkonfigurert. Vennligst kontroller dens  innstillinger",
      "SeverityLabel": "Alvorlighet",
      "ShowAllRelatedEvents": "Vis alle relaterete hendelser",
      "ShowCount": "Vis oppsummering",
      "ShowFolderFieldLabel": "Vis mapper",
      "ShowInactiveRelationFieldLabel": "Vis innaktive relasjoner",
      "ShowOnlyMyTasks": "Vis kun mine oppgaver",
      "ShowPercentage": "Vis prosent",
      "ShowSeverityVertical": "Vis alvorlighet loddret",
      "SiteCouldNotBeCreated": "Sitet kunne ikke opprettes",
      "SiteCreationIsUnderway": "Sitet blir opprettet",
      "SiteCreationStatusCouldNotBeCheckedDueToTheFollowingError": "Site opprettelses status kunne ikke sjekkes grunnet følgende feil",
      "Sorting": "Sortering",
      "Sources": "Kilder",
      "StageView": "Stadievisning",
      "Start": "Start",
      "StartDate": "Startdato",
      "StartedOn": "Dette stadie ble startet",
      "StartTime": "Starttid",
      "Status": "Status",
      "Subject": "Emne",
      "SuccessFullyLoaded": "Hentet korrekt",
      "Sunday": "søndag",
      "SundayShort": "s",
      "TabbedGrouping": "Gruppering",
      "TabbedView": "Fanebladsvisning",
      "TaskList": "Oppgaveliste",
      "TaskOverdue": "Oppgave er forsinket",
      "TaskOverviewPropertyPaneDescription": "Innstillinger for oppgaveoversikt web part",
      "Tasks": "Oppgaver",
      "TasksAreShown": "Oppgaver er vist",
      "TaskShown": "Oppgave er vist",
      "TasksOverdue": "Oppgaver er forsinket",
      "TextColorInTiles": "Tekst farve i kvadrater",
      "TheEntityCouldNotBeRecycled": "Entiteten kunne ikke fjernes. Prøv igjen og sjekk at entiteten ikke ligger i papirkurven",
      "TheEntityHasBeenRecycled": "Entiteten er fjernet",
      "Thursday": "torsdag",
      "ThursdayShort": "t",
      "Title": "Tittel",
      "To": "Til",
      "Today": "I dag",
      "Tuesday": "tirsdag",
      "TuesdayShort": "t",
      "UseDateSlider": "Brug dato-velger",
      "Version": "Versjon",
      "Viewed": "Kikket på",
      "Waiting": "Venter på en annen",
      "Wednesday": "onsdag",
      "WednesdayShort": "o",
      "Week": "Uke",
      "Weeks": "Uker",
      "WorkPoint365Administration": "WorkPoint 365 Administrasjon",
      "WorkPointSupportCenter": "WorkPoint Support Center",
      "Year": "År",
      "Years": "År",
      "Yes": "Ja",
      "You": "Du",
      "YouCanAlsoCreateATemplateWithoutMailMerge": "Du kan også opprette en mal uten forretningsmodul flettefelter",
      "YouDoNotHavePermissionToPerformThisAction": "Du har ikke rettigheter til å utføre denne handlingen",
      "YouHaveNoWorkPoint365License": "Du har ingen WorkPoint 365 lisens",
      "ZToA": "Z til A",
    }
  });