define([], function() {
    return {
      "Ago": "Terug",
      "AllActions": "Alle acties",
      "AllItems": "Alle items",
      "AllLabel": "Alle",
      "ApplyStageFilter": "Pas fase filter toe",
      "April": "april",
      "AprilShort": "apr",
      "AreYouSureYouWantToDeleteThis": "Weet u zeker dat u deze relatie wil verwijderen?",
      "AreYouSureYouWantToDeleteThisItem": "Weet u zeker dat u dit item wil verwijderen?",
      "AToZ": "A tot Z",
      "Attachment": "Bijlage",
      "Attachments": "Bijlagen",
      "August": "augustus",
      "AugustShort": "aug",
      "Author": "Auteur",
      "BasicGroupName": "Algemene instellingen",
      "Call": "Bel",
      "Cancel": "Annuleer",
      "Category": "Categorie",
      "Cc": "Cc",
      "ChangeStage": "Verander fase",
      "ChooseABusinessModuleToCreateWordTemplateFor": "Kies een Business Module om een Word sjabloon voor te maken",
      "Clear": "Wis",
      "ClearWorkPointBrowserCache": "Wis WorkPoint 365 browser cache",
      "Close": "Sluit",
      "CloseThisDialog": "Sluit de dialoog",
      "CollapseExpandEntityPanel": "Open / Sluit het entiteit venster",
      "Color": "Kleur",
      "ColorGroupName": "Kleuren van diagonalen",
      "Completed": "Voltooid",
      "ConfigureWebPart": "Configureer taakoverzicht web onderdeel",
      "ConstraintsPassedWhenStarted": "Bij het starten doorgegeven beperkingen",
      "Content": "Inhoud",
      "CurrentSite": "Huidige site",
      "Dashboards": "Dashboards",
      "Date": "Datum",
      "Day": "Dag",
      "Days": "Dagen",
      "DeadlineExceeded": "De deadlijn is overschreden",
      "DeadlineIs": "Deadline is ",
      "DeadlineSoon": "Deadline nadert",
      "DeadlineWas": "Deadline was",
      "December": "december",
      "DecemberShort": "dec",
      "Deferred": "Uitgesteld",
      "Delete": "Verwijder",
      "DeleteConfirmation": "Verwijder bevestiging",
      "Description": "Beschrijving",
      "Details": "Details",
      "Direction": "Richting",
      "DisplayAs": "Toon als",
      "DisplayGroupName": "Toon",
      "Documents": "Documenten",
      "Download": "Download",
      "DueDate": "Vervaldatum",
      "Edit": "Wijzig",
      "EditTemplate": "Wijzig sjabloon",
      "Emails": "E-mails",
      "EmailsEMM": "E-mails (EMM)",
      "EMMPropertyPaneDescription": "Instellingen voor het E-Mail Manager webonderdeel",
      "Enabled": "Ingeschakeld",
      "End": "Beëindig",
      "EndDate": "Einddatum",
      "EndTime": "Eindtijd",
      "EntireWorkPointSolution": "Gehele WorkPoint oplossing",
      "EntityFiltering": "Entiteit filtering",
      "EntitySite": "Entiteit site",
      "Events": "Gebeurtenissen",
      "ExternalUserLicenseDescription": "Externe gebruiker licentie",
      "February": "februari",
      "FebruaryShort": "feb",
      "Field": "Veld",
      "FileType": "Bestandstype",
      "FilterBy": "Filter op",
      "Filtering": "Filtert",
      "Filters": "Filters",
      "Friday": "vrijdag",
      "FridayShort": "Vrij",
      "From": "Van",
      "GeneralGroupName": "Algemene instellingen",
      "GoTo": "Ga naar",
      "GoToNextMonth": "Ga naar volgende maand",
      "GoToNextPage": "Ga naar volgende pagina",
      "GoToNextYear": "Ga naar volgend jaar",
      "GoToPreviousMonth": "Ga naar vorige maand",
      "GoToPreviousPage": "Ga naar vorige pagina",
      "GoToPreviousYear": "Ga naar vorig jaar",
      "GoToTheSiteFor": "Ga naar de site voor",
      "GoToToday": "Ga naar vandaag",
      "GoUp": "Ga omhoog",
      "GroupedListFieldLabel": "Toon relaties in gegroepeerde lijst",
      "Home": "Start",
      "Hour": "Uur",
      "Hours": "Uren",
      "IfYouRegretRecyclingEntityItCanBeRestored": "Als u zich bedenkt, kunt u herstellen vanuit de Prullenbak",
      "Images": "Afbeeldingen",
      "Incoming": "Inkomend",
      "InProgress": "In behandeling",
      "InSelectedList": "In geselecteerde ljst",
      "IsEqualToEntityField": "Is gelijk aan entiteit veld",
      "ItemLimitFieldLabel": "Beperkt het aantal per pagina getoonde e-mails",
      "January": "januari",
      "JanuaryShort": "jan",
      "JobFailed": "De opdracht is niet uitgevoerd",
      "JobSucceded": "De opdracht is uitgevoerd",
      "Journal": "Logboek",
      "JournalInfo": "Logboek info",
      "JournalPropertyPaneDescription": "Instellingen voor het Logboek webonderdeel",
      "July": "juli",
      "JulyShort": "jul",
      "June": "juni",
      "JuneShort": "jun",
      "JustNow": "Zo pas",
      "LastModified": "Laatst gewijzigd",
      "LicensedUserDescription": "Gelicentiëerde gebruiker",
      "LimitedLicenseDescription": "Beperkte gebruiker licentie",
      "LinkToItem": "Snelkoppeling naar item",
      "List": "Lijst",
      "ListViewPropertyPaneDescription": "Instellingen voor het WorkPoint lijstweergave client side webonderdeel.",
      "Loading": "Haalt op",
      "LoadingRelations": "Haalt relaties op",
      "Location": "Locatie",
      "LookupField": "Opzoek veld",
      "March": "maart",
      "MarchShort": "mar",
      "May": "mei",
      "MayShort": "mei",
      "Minute": "Minuut",
      "Minutes": "Minuten",
      "Modified": "Gewijzigd",
      "Monday": "maandag",
      "MondayShort": "Ma",
      "Month": "Maand",
      "Months": "Maanden",
      "MoreActions": "Meer acties",
      "MoreUsers": "Meer gebruikers",
      "MyWorkPointSolution": "Mijn WorkPoint oplossing",
      "NavigateToTheBusinessModuleWhereEntityWasRecycled": "Naar de business module navigeren waartoe het item behoort?",
      "NeedHelp": "Hulp nodig",
      "NewWordTemplate": "Nieuw Word sjabloon",
      "No": "Nee",
      "NoActivity": "Geen activiteit voor deze entiteit",
      "NoEntityFiltering": "Geen entiteit filtering",
      "NoItems": "Er zijn hier geen items om te tonen.",
      "NoItemsToShowHere": "Geen items om te tonen",
      "NoLicenseDescription": "Geen licentie voor deze gebruiker",
      "None": "Geen",
      "NoSettings": "Er zijn geen instellingen voor dit webonderdeel.",
      "NotStarted": "Niet gestart",
      "November": "november",
      "NovemberShort": "nov",
      "NumberOfItemsShown": "Aantal getoonde items",
      "October": "oktober",
      "OctoberShort": "okt",
      "Ok": "OK",
      "Open": "Open",
      "OpenANewMailComposerToTheAddress": "Open een nieuwe e-mail naar dit adres",
      "OpenLinkTo": "Open koppeling naar",
      "OpenStageLink": "Open fase koppeling",
      "OpenTemplate": "Open sjabloon",
      "Outgoing": "Uitgaand",
      "ParentSite": "Bovenliggende site",
      "PercentComplete": "% compleet",
      "Preview": "Voorbeeld",
      "ProbabilityLabel": "Waarschijnlijkheid",
      "ReallyDeleteThisSite": "Weet u zeker dat u deze site wil verwijderen?",
      "ReallyRecycleThisEntity": "Weet u zeker dat u deze entiteit wil verwijderen?",
      "Relation": "Relatie",
      "RelationPropertyPaneDescription": "Instellingen voor het WorkPoint 365 Relatie client side webonderdeel.",
      "Relations": "Relaties",
      "RelationTypeFieldLabel": "Relatie types",
      "RemoveStageFilter": "Verwijder fase filter",
      "Responsible": "Verantwoordelijke",
      "RiskMatrixPropertyPaneDescription": "Instellingen voor het Risico Matrix client siide webonderdeel.",
      "RootSite": "Root site",
      "Saturday": "zaterdag",
      "SaturdayShort": "Za",
      "Scope": "Bereik",
      "SelectA": "Selecteer een",
      "SelectACustomDate": "Selecteer een datum",
      "SelectEndDate": "Selecteer einddatum",
      "SelectList": "Selecteer lijst",
      "SelectProbability": "Selecteer veld voor waarschijnlijkheid",
      "SelectSeverity": "Selecteer veld voor gewicht",
      "SelectStartDate": "Selecteer startdatum",
      "SelectView": "Selecteer weergave in de lijst",
      "Sender": "Afzender",
      "Sent": "Verzonden",
      "September": "september",
      "SeptemberShort": "sep",
      "SettingsError": "Er ging iets mis met de web eigenschappen.",
      "SeverityLabel": "Gewicht",
      "ShowAllRelatedEvents": "Toon alle gerelateerde gebeurtenissen",
      "ShowCount": "Toon aantal",
      "ShowFolderFieldLabel": "Toon mappen",
      "ShowInactiveRelationFieldLabel": "Toon inactieve relaties",
      "ShowOnlyMyTasks": "Toon alleen mijn taken",
      "ShowPercentage": "Toon percentage",
      "ShowSeverityVertical": "Toon het Gewicht verticaal",
      "SiteCouldNotBeCreated": "Site kon niet worden gemaakt",
      "SiteCreationIsUnderway": "Site wordt gemaakt",
      "SiteCreationStatusCouldNotBeCheckedDueToTheFollowingError": "Site creatie status kon niet worden gecontroleerd a.g.v. de volgende fout",
      "Sorting": "Sorteert",
      "Sources": "Bronnen",
      "StageView": "Fase weergave",
      "Start": "Start",
      "StartDate": "Startdatum",
      "StartedOn": "Start deze fase op",
      "StartTime": "Starttijd",
      "Status": "Status",
      "Subject": "Onderwerp",
      "SuccessFullyLoaded": "Succesvol geladen",
      "Sunday": "zondag",
      "SundayShort": "Zo",
      "TabbedGrouping": "Groepeert",
      "TabbedView": "Tabbladen weergave",
      "TaskList": "Takenlijst",
      "TaskOverdue": "Achterstallige taak",
      "TaskOverviewPropertyPaneDescription": "Instellingen voor het takenoverzicht webonderdeel",
      "Tasks": "Taken",
      "TasksAreShown": "Taken worden getoond",
      "TaskShown": "Taak wordt getoond",
      "TasksOverdue": "Achterstallige taken",
      "TextColorInTiles": "Tekstkleur in tegels",
      "TheEntityCouldNotBeRecycled": "De entteit kon niet worden verwijderd, probeer het opnieuw of zorg dat het item zich niet in de Prullenbak bevindt",
      "TheEntityHasBeenRecycled": "De entiteit is verwijderd",
      "Thursday": "donderdag",
      "ThursdayShort": "Do",
      "Title": "Titel",
      "To": "Tot",
      "Today": "Vandaag",
      "Tuesday": "Dinsdag",
      "TuesdayShort": "Di",
      "UseDateSlider": "Gebruik datumschuif",
      "Version": "Versie",
      "Viewed": "Bekeken",
      "Waiting": "Wacht op",
      "Wednesday": "woensdag",
      "WednesdayShort": "Wo",
      "Week": "Week",
      "Weeks": "Weken",
      "WorkPoint365Administration": "WorkPoint 365 Beheer",
      "WorkPointSupportCenter": "WorkPoint Support Center",
      "Year": "Jaar",
      "Years": "Jaren",
      "Yes": "Ja",
      "You": "U",
      "YouCanAlsoCreateATemplateWithoutMailMerge": "U kunt ook een sjabloon maken zonder business module mail merge velden",
      "YouDoNotHavePermissionToPerformThisAction": "U heeft onvoldoende rechten om deze actie uit te voeren",
      "YouHaveNoWorkPoint365License": "U heeft geen WorkPoint 365 licentie",
      "ZToA": "Z tot A",
    }
  });